version: '3.8'

services:
  app:
    build: .
    ports:
      - "7200:7200"
    environment:
      # Spring Boot application database connection
      SPRING_DATASOURCE_URL: jdbc:mysql://cc-database.c6woo9nomrhf.us-east-1.rds.amazonaws.com:3306/openingjobs
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: AVDnjkJgz33nvyq6uJVF

    volumes:
      - app-logs:/app/logs  # Optional: to persist application logs

    # Persistent MySQL data

volumes:

  # Persistent storage for MySQL data
  app-logs:
  # Optional: storage for application logs